language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - "pypy"
before_install:
    - sudo pip install iptools --use-mirrors
install:
    - sudo python setup.py install
script: make test
notifications:
    email: false