language: python
python:
    - 2.6
    - 2.7
    - pypy
    - 3.2
    - 3.3
    - 3.4
before_install:
    - sudo pip install iptools
install:
    - sudo python setup.py install
script: make test
notifications:
    email: false