language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
virtualenv:
  system_site_packages: true
before_install:
  - "sudo pip install iptools"
install:
  - "sudo python setup.py install"
script: make test